### ISSUE TITLE
[feat] auto-cloze with hint

### ISSUE THREAD

**Issue by AdrienLemaire** [Joseph-Y/godmode#1]
Hi @Joseph-Y and thanks for making and maintaining God mode, the last month was hard without it :)

Is there a way to add an option "editor cloze with hint", that would auto-copy the text to the hint field?

I'm currently doing this operation ~100 times per day

1. Ctrl+E on word
2. Select `::word`, copy-paste it
3. Select cloze text, Ctrl-U to underline
4. Add the `reading ` or `meaning ` prefix to the hint.

Example from:
```
犯罪を犯す
```
Cloze 1:
```
{{c1::<u>犯罪</u>::reading 犯罪}}を{{c2::<u>犯す</u>::reading 犯す}}
```
Cloze 2:
```
{{c1::<u>犯罪</u>::meaning 犯罪}}を{{c2::<u>犯す</u>::meaning 犯す}}
```

It would make my life easier if I could shorten the steps needed to create new clozes :) Thanks for considering it, or for teaching me how to do this by myself.

**Comment by Joseph-Y** [comment]
Hey Adrien. If I understand your use case correctly, here are two possible solutions:

1. Make a card template that underlines and adds prefixes to predefined fields. That way all you have to enter is the word into the card fields, and the template takes care of the rest for you. This video touches on that starting after 3 minutes: https://www.youtube.com/watch?v=AnEJOb6wueI

2. If you have a Mac, maybe try to make an Automator workflow for this repetitive task. 

I don't see an easy solution that I can code into this addon. 

幸運を!

**Comment by AdrienLemaire** [comment]
You're right, should have gone with the template from the beginning ^^ Many thanks for the quick reply!
