### ISSUE TITLE
Doesn't work with "Edit Field During Review (Cloze)

### ISSUE THREAD

**Issue by mytestingsolution** [Joseph-Y/godmode#3]
Hi,

I absolutely love this add on...it is seriously one of my favorites. I used to have resistance to making that extra cloze just because of the hassle of it, but now it's so easy...one of the best add-ons.

I noticed however that the shortcuts don't work when I'm using Edit Field During Review (Cloze) https://ankiweb.net/shared/info/385888438 which a lot of people use these days. I disabled all my other plugins except these two and it still didn't work. Any thoughts?

Thanks so much for your contribution!

**Comment by Joseph-Y** [comment]
Hey there! Happy to hear this helps!

Thanks for reporting the conflict. I don't use the other add-on, but from reading the description, I suspect it does its own shortcut remapping such that I don't think there's an easy fix to this problem. (You can see the problematic key remapping in that addon's code around line 220 [here](https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/blob/5b48455267ceb67886c070792beccccfc1d3dc77/edit_field_during_review_cloze/web/global_card.js)).

I only code things I personally use, so I don't plan to look into a fix. 

But if you or others want to look into a fix, I'd guess one way might be to combine the code from the two add-ons; then rewrite the Cloze shortcuts in the Edit Field add-on to be what they are in the Godmode add-on, so they don't conflict.

**Comment by mytestingsolution** [comment]
Okay! Thank you for the response!
